Repository honeycombio/honeycomb-opentelemetry-dotnet, pull requests merged in 2021-08, with the labels that each got.

#87 Trim commit hash from honeycomb.distro.version attribute
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
Labels: type: bug, version: bump minor

#90 Add OSS lifecycle badge
  OSSMETADATA
  README.md
Labels: version: no bump

#97 Allow dependabot and forked PRs to run in CI
  .circleci/config.yml
Labels: type: maintenance, version: no bump
