Repository honeycombio/honeycomb-opentelemetry-dotnet, pull requests merged in 2021-07, with the labels that each got.

#63 Prep 0.10.0 alpha release
  .circleci/config.yml
  CHANGELOG.md
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
Labels: status: review needed, type: maintenance

#64 Publish everything in build folder
  .circleci/config.yml
Labels: type: maintenance

#65 Publish specific suffix .nupkg
  .circleci/config.yml
Labels: type: maintenance

#69 Fix typos in README
  README.md
Labels: type: documentation, version: no bump

#66 Add redis instrumentation
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
Labels: type: enhancement, version: bump minor

#76 Add ASP.NET instrumentation
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
  src/Honeycomb.OpenTelemetry/ServiceCollectionExtensions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
Labels: type: enhancement, version: bump minor
