Repository honeycombio/honeycomb-opentelemetry-dotnet, pull requests merged in 2021-12, with the labels that each got.

#150 fix: Fixed Redis auto-detection
  src/Honeycomb.OpenTelemetry/ServiceCollectionExtensions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
Labels: type: bug, version: bump patch

#153 Prepare v0.15.0 release
  CHANGELOG.md
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
Labels: type: maintenance, version: bump minor

#154 parse missing command line arguments
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
  test/Honeycomb.OpenTelemetry.Tests/HoneycombOptionsTests.cs
  test/Honeycomb.OpenTelemetry.Tests/appsettings.test.json
Labels: type: bug, version: bump minor

#146 Add support for enabling OTLP metrics
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
  src/Honeycomb.OpenTelemetry/ResourceBuilderExtensions.cs
  src/Honeycomb.OpenTelemetry/ServiceCollectionExtensions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
  test/Honeycomb.OpenTelemetry.Tests/HoneycombOptionsTests.cs
  test/Honeycomb.OpenTelemetry.Tests/appsettings.test.json
Labels: type: enhancement, version: bump minor

#156 bug: trace extension should use trace config
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
Labels: type: bug, version: bump patch

#157 update example console app to use metrics
  examples/console/Program.cs
Labels: type: documentation, version: no bump

#155 Re-add net461 target framework
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
Labels: type: bug, version: bump minor

#159 Prepare v0.16.0-beta release
  CHANGELOG.md
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
Labels: type: maintenance, version: bump minor

#158 update example core app to use metrics
  examples/aspnetcore/Controllers/WeatherForecastController.cs
  examples/aspnetcore/Startup.cs
  examples/aspnetcore/appsettings.json
Labels: type: documentation, version: no bump

#161 Make API key and dataset optional
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
Labels: version: bump minor

#162 Prepare 0.17.0-beta release
  CHANGELOG.md
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
Labels: type: maintenance, version: no bump

#164 remove parent-based sampler
  src/Honeycomb.OpenTelemetry/DeterministicSampler.cs
Labels: version: bump minor

#165 Prepare v0.18.0-beta
  CHANGELOG.md
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
Labels: type: maintenance, version: no bump
