Repository honeycombio/honeycomb-opentelemetry-dotnet, pull requests merged in 2021-11, with the labels that each got.

#129 Allow the user to choose which type of clients to instrument and allow advanced configuration.
  README.md
  examples/netcoreapp2.1/Startup.cs
  examples/netcoreapp2.1/appsettings.json
  examples/netcoreapp2.1/netcoreapp2.1.csproj
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  src/Honeycomb.OpenTelemetry/ServiceCollectionExtensions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
  test/Honeycomb.OpenTelemetry.Tests/HoneycombOptionsTests.cs
Labels: type: enhancement, status: revision needed

#137 [fix] Remove whitespace failing build
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
Labels: type: bug, version: bump patch

#142 docs: update docs when releasing
  RELEASING.md
Labels: type: documentation, version: no bump, merge at will

#147 Update dependabot.yml
  .github/dependabot.yml
Labels: type: maintenance, version: no bump, merge at will

#145 Update DeterminisitcSampler to use OTel core Parent/TraceIDRatio samplers
  src/Honeycomb.OpenTelemetry/DeterministicSampler.cs
  test/Honeycomb.OpenTelemetry.Tests/DeterministicSamplerTests.cs
Labels: type: enhancement, version: bump minor
