Repository honeycombio/honeycomb-opentelemetry-dotnet, pull requests merged in 2022-09, with the labels that each got.

#246 Specify OTel version in README
  README.md
Labels: type: documentation, version: no bump

#245 Add support for `OTEL_SERVICE_NAME` environment variable
  src/Honeycomb.OpenTelemetry/EnvironmentOptions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
  test/Honeycomb.OpenTelemetry.Tests/EnvironmentOptionsTests.cs
Labels: type: bug, version: bump minor

#243 maint: dockerize example and prep for smoke tests, target .NET6
  .circleci/config.yml
  Makefile
  examples/aspnetcore-redis/aspnetcoreredis.csproj
  examples/aspnetcore/.dockerignore
  examples/aspnetcore/Dockerfile
  examples/aspnetcore/aspnetcore.csproj
  examples/console/console.csproj
  smoke-tests/apps/.gitkeep
  smoke-tests/collector/data-results/.gitkeep
  smoke-tests/collector/otel-collector-config.yaml
  smoke-tests/docker-compose.yml
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
  src/Honeycomb.OpenTelemetry/ServiceCollectionExtensions.cs
  test/Honeycomb.OpenTelemetry.Tests/Honeycomb.OpenTelemetry.Tests.csproj
Labels: type: enhancement, type: maintenance, version: bump minor

#247 Phillip's petty code changes to be more idiomatic
  src/Honeycomb.OpenTelemetry/BaggageSpanProcessor.cs
  src/Honeycomb.OpenTelemetry/ConsoleTraceLinkExporter.cs
  src/Honeycomb.OpenTelemetry/EnvironmentOptions.cs
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  src/Honeycomb.OpenTelemetry/HoneycombOptionsExtensions.cs
  src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
  src/Honeycomb.OpenTelemetry/ServiceCollectionExtensions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
Labels: type: maintenance, version: bump patch

#249 Attempt to match Java distro resources
  src/Honeycomb.OpenTelemetry/ResourceBuilderExtensions.cs
Labels: type: enhancement, version: bump minor

#254 Support debug option
  src/Honeycomb.OpenTelemetry/EnvironmentOptions.cs
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
  test/Honeycomb.OpenTelemetry.Tests/EnvironmentOptionsTests.cs
  test/Honeycomb.OpenTelemetry.Tests/HoneycombOptionsTests.cs
  test/Honeycomb.OpenTelemetry.Tests/appsettings.test.json
Labels: type: enhancement, status: revision needed, version: bump minor

#255 Add AspNetCore instrumentation extension to add baggage to new spans
  examples/aspnetcore-redis/Startup.cs
  examples/aspnetcore-redis/aspnetcoreredis.csproj
  examples/aspnetcore/Startup.cs
  examples/aspnetcore/aspnetcore.csproj
  honeycomb-opentelemetry.sln
  src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore.csproj
  src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/TracerProviderBuilderExtensions.cs
Labels: type: enhancement, version: bump minor

#262 Add Tracer to DI in AspNetCore examples
  examples/aspnetcore-redis/Startup.cs
  examples/aspnetcore-redis/appsettings.json
  examples/aspnetcore/Startup.cs
  examples/aspnetcore/appsettings.json
Labels: type: maintenance, version: bump minor

#263 Add http/protobuf smoke tests
  .gitignore
  Makefile
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-sdk-http.bats
  smoke-tests/test_helpers/utilities.bash
Labels: type: maintenance, version: no bump

#270 Add Honeycomb.OpenTelemetry.Autoinstrumentations
  honeycomb-opentelemetry.sln
  src/Honeycomb.OpenTelemetry.AutoInstrumentations/Honeycomb.OpenTelemetry.AutoInstrumentations.csproj
  src/Honeycomb.OpenTelemetry.AutoInstrumentations/TracerProviderBuilderExtensions.cs
  src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore.csproj
Labels: type: enhancement, version: bump minor

#268 Add make targets for smoke tests & set up CI smoke tests
  .circleci/config.yml
  Makefile
  smoke-tests/apps/.gitkeep
Labels: type: maintenance

#276 Move extensions into owning class namespace & rename add instrumentations ext method
  src/Honeycomb.OpenTelemetry.AutoInstrumentations/TracerProviderBuilderExtensions.cs
  src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
  src/Honeycomb.OpenTelemetry/ResourceBuilderExtensions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
Labels: type: enhancement, version: bump major

#280 Add ConfigurationManager extension methods
  examples/aspnetcore-redis/Program.cs
  examples/aspnetcore/Program.cs
  src/Honeycomb.OpenTelemetry/WebApplicationBuilderExtensions.cs
Labels: type: enhancement

#281 Update aspnetcore example to send metrics
  examples/aspnetcore/Program.cs
  src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
Labels: type: maintenance

#282 Remove custom command line argument parsing
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
  test/Honeycomb.OpenTelemetry.Tests/HoneycombOptionsTests.cs
Labels: type: maintenance

#279 Append traces path to http endpoint
  smoke-tests/docker-compose.yml
  src/Honeycomb.OpenTelemetry/EnvironmentOptions.cs
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  src/Honeycomb.OpenTelemetry/MeterProviderBuilderExtensions.cs
  src/Honeycomb.OpenTelemetry/TracerProviderBuilderExtensions.cs
  test/Honeycomb.OpenTelemetry.Tests/EnvironmentOptionsTests.cs
  test/Honeycomb.OpenTelemetry.Tests/HoneycombOptionsTests.cs
Labels: type: bug, version: bump minor

#284 Append /v1/metrics to endpoint path if the protocol is HTTP
  smoke-tests/collector/otel-collector-config.yaml
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-sdk-grpc.bats
  smoke-tests/smoke-sdk-http.bats
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  test/Honeycomb.OpenTelemetry.Tests/HoneycombOptionsTests.cs
Labels: type: bug, version: bump minor

#285 Add CircleCI context for nightly package step
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#273 Prepare v1.0.0/0.24.0 releases
  CHANGELOG.md
  src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore.csproj
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
Labels: type: maintenance, version: bump major
