Repository honeycombio/honeycomb-opentelemetry-dotnet, pull requests merged in 2022-10, with the labels that each got.

#294 [ci] Fix nightly build
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#299 maint: add release file
  .github/release.yml
Labels: type: maintenance, version: no bump, merge at will, no-changelog

#298 De-bump Npgsql.OpenTelemetry to 6.0.7 to avoid collisions with LTS entityframework
  src/Honeycomb.OpenTelemetry.AutoInstrumentations/Honeycomb.OpenTelemetry.AutoInstrumentations.csproj
Labels: type: bug, version: bump minor

#296 Add F# example? ( ･ω･)
  examples/aspnetcore-fsharp/Program.fs
  examples/aspnetcore-fsharp/README.md
  examples/aspnetcore-fsharp/Routing.fs
  examples/aspnetcore-fsharp/appsettings.json
  examples/aspnetcore-fsharp/aspnetcore-fsharp.fsproj
  examples/aspnetcore-fsharp/my-web-app.png
  examples/aspnetcore-redis/appsettings.json
  examples/aspnetcore/appsettings.json
  honeycomb-opentelemetry.sln
Labels: version: no bump

#308 maint: delete workflows for old board
  .github/workflows/add-to-project.yml
  .github/workflows/re-triage.yml
Labels: type: maintenance, version: no bump, merge at will, no-changelog

#305 maint: exclude package job on PRs from forks & dependabot
  .circleci/config.yml
Labels: type: maintenance, version: no bump, no-changelog

#309 maint: fix fork filter to ignore branches instead of tags
  .circleci/config.yml
Labels: type: maintenance, version: no bump, no-changelog

#306 Update OTel hosting & instrumentation packages
  examples/aspnetcore-fsharp/aspnetcore-fsharp.fsproj
  examples/aspnetcore-redis/aspnetcoreredis.csproj
  examples/aspnetcore/aspnetcore.csproj
  src/Honeycomb.OpenTelemetry.AutoInstrumentations/Honeycomb.OpenTelemetry.AutoInstrumentations.csproj
  src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore.csproj
Labels: type: maintenance, version: bump patch

#310 prepare 1.1.0 release
  CHANGELOG.md
  RELEASING.md
  src/Honeycomb.OpenTelemetry.AutoInstrumentations/Honeycomb.OpenTelemetry.AutoInstrumentations.csproj
  src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore.csproj
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  test/Honeycomb.OpenTelemetry.Tests/HoneycombOptionsExtensionsTests.cs
Labels: no-changelog

#311 maint: fix ci publish pipeline
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#313 Update README.md
  examples/aspnetcore-fsharp/README.md
Labels: type: documentation, version: no bump
