Repository honeycombio/honeycomb-opentelemetry-dotnet, pull requests merged in 2022-11, with the labels that each got.

#317 IConfiguration for Honeycomb Options
  src/Honeycomb.OpenTelemetry/WebApplicationBuilderExtensions.cs
Labels: type: enhancement, version: bump patch, status: oncall

#320 fix: metrics smoke tests
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-sdk-grpc.bats
  smoke-tests/smoke-sdk-http.bats
Labels: type: bug, version: no bump, no-changelog

#319 Update aspnetcore instrumentation to 1.0.0-rc9.9
  src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore.csproj
  src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/TracerProviderBuilderExtensions.cs
Labels: type: maintenance, version: bump patch

#318 Bump instrumentation pacakges to 1.0.0-rc9.9
  examples/aspnetcore-fsharp/aspnetcore-fsharp.fsproj
  examples/aspnetcore-redis/aspnetcoreredis.csproj
  examples/aspnetcore/aspnetcore.csproj
  src/Honeycomb.OpenTelemetry.AutoInstrumentations/Honeycomb.OpenTelemetry.AutoInstrumentations.csproj
Labels: type: maintenance, version: bump patch

#321 Prepare v1.2.0 / v0.26.0 release
  CHANGELOG.md
  src/Honeycomb.OpenTelemetry.AutoInstrumentations/Honeycomb.OpenTelemetry.AutoInstrumentations.csproj
  src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore.csproj
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
Labels: type: maintenance, version: bump minor

#323 fix: Only add Redis instrumentation if connection found in DI
  src/Honeycomb.OpenTelemetry.AutoInstrumentations/TracerProviderBuilderExtensions.cs
Labels: type: bug, version: bump patch

#324 Prepare v1.2.1/0.26.1-beta release
  CHANGELOG.md
  src/Honeycomb.OpenTelemetry.AutoInstrumentations/Honeycomb.OpenTelemetry.AutoInstrumentations.csproj
  src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore.csproj
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
Labels: type: maintenance, version: bump patch

#325 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#326 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog, version: no-bump
