Repository honeycombio/honeycomb-opentelemetry-dotnet, pull requests merged in 2024-03, with the labels that each got.

#371 feat: support classic ingest keys
  .circleci/config.yml
  src/Honeycomb.OpenTelemetry/HoneycombOptions.cs
  test/Honeycomb.OpenTelemetry.Tests/HoneycombOptionsTests.cs
Labels: type: enhancement, version: bump minor

#372 rel: prepare 1.5.0 release
  CHANGELOG.md
  src/Honeycomb.OpenTelemetry.CommonInstrumentations/Honeycomb.OpenTelemetry.CommonInstrumentations.csproj
  src/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore/Honeycomb.OpenTelemetry.Instrumentation.AspNetCore.csproj
  src/Honeycomb.OpenTelemetry/Honeycomb.OpenTelemetry.csproj
Labels: type: maintenance, merge at will, no-changelog

#373 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: type: maintenance, version: no bump, merge at will, no-changelog

#375 maint: Update README with latest OTel SDK version
  .gitignore
  README.md
Labels: type: maintenance, version: no bump
